In [6]:
import random
import numpy as np  # Q러닝에서 np.argmax를 사용해서 가져옴

## GridWorld 클래스

In [3]:
class GridWorld(): # 그리드월드 클래스 생성
    def __init__(self): # 초기 변수 x, y (그리드 월드 시작 state)
        self.x = 0
        self.y = 0

    def step(self, a):
        # 0번 액션: 왼쪽, 1번 액션: 위, 2번 액션: 오른쪽, 3번 액션 : 아래쪽
        if a==0:
            self.move_left() # 각 이동함수를 통해서 현재 state의 좌표를 변환한다.
        elif a==1:
            self.move_up()
        elif a==2:
            self.move_right()
        elif a==3:
            self.move_down()
    
        reward = -1 #보상은 1로 고정 (MDP를 모르므로 실제 관측하기 전까지는 모른다고 가정)
        done = self.is_done() # done을 불리언으로 판정 terminal state 판단을 위해
        return (self.x, self.y), reward, done

    def move_left(self):
        if self.y==0: #벽(테두리)지정
            pass
        elif self.y==3 and self.x in [0, 1, 2]: #장애물도 마찬가지로 지정해준다.
            pass
        elif self.y==5 and self.x in [2, 3, 4]:
            pass
        else:
            self.y -=1

    def move_right(self):
        if self.y==1 and self.x in [0, 1, 2]:
            pass
        elif self.y==3 and self.x in [2, 3, 4]:
            pass
        elif self.y==6:
            pass
        else:
            self.y +=1

    def move_up(self):
        if self.x==0:
            pass
        elif self.x==3 and self.y==2:
            pass
        else:
            self.x -= 1

    def move_down(self):
        if self.x==4:
            pass
        elif self.x==1 and self.y==4:
            pass
        else:
            self.x+=1
    
    def is_done(self):
        if self.x==4 and self.y==6: # 목표 state인 (4, 6)에 도달하면 끝난다.
            return True
        else:
            return False
    
    def reset(self): #시작 state로 돌아가는 함수
        self.x = 0
        self.y = 0
        return (self.x, self.y)

## MC QAgent 클래스

In [ ]:
class QAgent():
    def __init__(self):
        self.q_table = np.zeros((5, 7, 4)) 
        #q밸류를 저장하는 변수, 모두 0으로 초기화해준다.
        # 상태가치함수가 아니라 행동가치함수를 찾기위해 마지막 상하좌우 행동에 따른 가치 차원을 추가해줌
        #좌표는 (그리드의 행, 그리드의 열, 상하좌우 행동 가치)로 이루어진다
        self.eps = 0.9 #엡실론
        self.alpha = 0.01 #알파
    
    def select_action(self, s):
        # 엡실론-그리디로 액션 선택
        x, y = s
        coin = random.random() # 0~1사이의 실수를 랜덤하게 뽑아줌
        if coin < self.eps: #랜덤연산을 통해 엡실론 이하값이 나오는 경우
            action = random.randint(0,3) #이동은 상하좌우 중 랜덤하게 선택
        else:
            action_val = self.q_table[x,y,:] #현재 x,y좌표의 q_table을 변수에 저장
            action = np.argmax(action_val) #그중 제일 가치가 큰 행동을 선택해서 그쪽으로 이동함 (그리디 행동)
        return action
    
    def update_table(self, history):
        # 한 에피소드에 해당하는 history를 입력으로 받아 q 테이블의 값을 업데이트 한다.
        cum_reward = 0   #누적 리워드 = 리턴
        for transition in history[::-1]:  # 에피소드가 끝나면 역순으로 리턴을 체크해서
            s, a, r , s_prime = transition
            x, y = s  # state 확인 후
            self.q_table[x,y,a] = self.q_table[x,y,a] + self.alpha * (cum_reward - self.q_table[x,y,a]) #해당 state(x,y 좌표에 해당하는 action의 q-table을 업데이트 해준다.
            cum_reward = cum_reward + r

    def anneal_eps(self):
        self.eps -= 0.03 #한번 호출될때마다 입실론 값이0.03씩 내려감
        self.eps = max(self.eps, 0.1) #최소 0.1은 보장
    
    def show_table(self):
        # 학습이 각 위치에서 어느 액션의 q값이 가장 높았는지 보여주는 함수 (뭔소리?)
        q_lst = self.q_table.tolist()  #넘파이어레이 리스트로 바꿔줌
        data = np.zeros((5, 7))
        for row_idx in range(len(q_lst)):
            row = q_lst[row_idx]
            for col_idx in range(len(row)):
                col = row[col_idx]
                action = np.argmax(col)
                data[row_idx, col_idx] = action
        print(data)

## 메인 함수

In [ ]:
def main():
    env = GridWorld()
    agent = QAgent()
    episode = 1000

    for n_epi in range(episode): #1000번 에피소드
        done = False
        history = []

        s = env.reset()
        while not done: # 한 에피소드가 끝날때 까지
            a = agent.select_action(s)
            s_prime, r, done = env.step(a)
            history.append((s, a, r, s_prime))
            s = s_prime
        agent.update_table(history) #히스토리를 이용하여 에이전트를 업데이트
        agent.anneal_eps()

    agent.show_table()
    

In [ ]:
main()

[[2. 3. 0. 2. 2. 3. 0.]
 [3. 3. 0. 2. 1. 3. 3.]
 [3. 3. 0. 1. 0. 3. 3.]
 [3. 2. 3. 1. 0. 2. 3.]
 [2. 1. 2. 1. 0. 2. 0.]]


각각 상하좌우 어디로 이동하는게 베스트인지를 알려주는 최적 정책 π*를 보여준다

다시말해 매 그리드마다 q(s,a)가 높은 액션을 표시한 것이다.

## SARSA (MC대신 TD 사용)

In [ ]:
class QAgent():
    def __init__(self):
        self.q_table = np.zeros((5, 7, 4)) #마찬가지로 q밸류가 추가되어 3차원이다.
        self.eps = 0.9 
    
    def select_action(self, s):
        # 엡실론-그리디로 액션 선택
        x, y = s
        coin = random.random()
        if coin < self.eps:
            action = random.randint(0,3)
        else:
            action_val = self.q_table[x,y,:]
            action = np.argmax(action_val)
        return action
    
    # 나머지는 같고 table을 업데이트 하는 방식만 바꿔준당
    def update_table(self, transition):
        s, a, r , s_prime = transition  #history 대신 바로 transition을 사용 (바로 업데이트 할꺼니깐)
        x, y = s
        next_x, next_y = s_prime
        a_prime = self.select_action(s_prime) # s'에서 선택할 액션을 미리 체크함
        #SARSA 업데이트 식을 이용
        self.q_table[x,y,a] = self.q_table[x,y,a] + 0.1*(r + self.q_table[next_x, next_y, a_prime] - self.q_table[x,y,a])

    def anneal_eps(self):
        self.eps -= 0.03 #한번 호출될때마다 0.03씩 내려감
        self.eps = max(self.eps, 0.1) #최소 0.1은 보장
    
    def show_table(self):
        # 학습이 각 위치에서 어느 액션의 q값이 가장 높았는지 보여주는 함수 (뭔소리?)
        q_lst = self.q_table.tolist()  #넘파이어레이 리스트로 바꿔줌
        data = np.zeros((5, 7))
        for row_idx in range(len(q_lst)):
            row = q_lst[row_idx]
            for col_idx in range(len(row)):
                col = row[col_idx]
                action = np.argmax(col)
                data[row_idx, col_idx] = action
        print(data)

In [4]:
def main():
    env = GridWorld()
    agent = QAgent()
    episode = 1000

    for n_epi in range(episode): #1000번 에피소드
        done = False

        s = env.reset()
        while not done: # 한 에피소드가 끝날때 까지
            a = agent.select_action(s)
            s_prime, r, done = env.step(a)
            agent.update_table((s, a, r, s_prime))
            s = s_prime
        agent.anneal_eps()

    agent.show_table()
'''
history에 리스트를 모아서 한번에 바꿔준 이전과 다르게
매번 update_table을 호출해서 바꿔주는 것으로 TD, MC 차이를 확인가능
'''

'\nhistory에 리스트를 모아서 한번에 바꿔준 이전과 다르게\n매번 update_table을 호출해서 바꿔주는 것으로 TD, MC 차이를 확인가능\n'

In [ ]:
main()

[[2. 3. 0. 2. 2. 2. 3.]
 [3. 3. 0. 2. 2. 3. 3.]
 [3. 3. 0. 1. 0. 3. 3.]
 [2. 2. 2. 1. 0. 3. 3.]
 [3. 2. 2. 1. 0. 2. 0.]]


수렴한 값은 비슷... 좌하단 구석에 잘못된 방향을 가리키고 있는 것을 볼수 있음


-> 최적해는 구했지만 탐색이 부족했다.

## Q러닝 QAgent

Class GridWorld () <- 환경이므로 건드릴 필요 없슴


In [1]:
class QAgent():
    def __init__(self):
        self.q_table = np.zeros((5, 7, 4)) #q밸류를 저장하는 변수, 모두 0이고 3차원임
        self.eps = 0.9 
    
    def select_action(self, s):
        # 엡실론-그리디로 액션 선택
        x, y = s
        coin = random.random()
        if coin < self.eps:
            action = random.randint(0,3)
        else:
            action_val = self.q_table[x,y,:]
            action = np.argmax(action_val)
        return action

    def update_table(self, transition):
        s, a, r , s_prime = transition
        x, y = s
        next_x, next_y = s_prime
        a_prime = self.select_action(s_prime) 
        #SARSA대신 Q러닝 업데이트 식을 이용
        self.q_table[x,y,a] = self.q_table[x,y,a] + 0.1*(r + np.max(self.q_table[next_x, next_y, :]) - self.q_table[x,y,a])
        #공식에 따라서 SARSA에서는 그냥 다음 액션의 Q_table을 가져오던 것에서 다음 Q_table의 max를 가져오는것으로 바뀜

    def anneal_eps(self):
        self.eps -= 0.01 #q러닝에서는 epsilon이 더 천천히 줄어들도록 함(왜?)
        self.eps = max(self.eps, 0.2) # 0.2도 더 크다(왜?)

    def show_table(self):
        q_lst = self.q_table.tolist()  
        data = np.zeros((5, 7))
        for row_idx in range(len(q_lst)):
            row = q_lst[row_idx]
            for col_idx in range(len(row)):
                col = row[col_idx]
                action = np.argmax(col)
                data[row_idx, col_idx] = action
        print(data)

In [7]:
main()

[[2. 3. 0. 2. 3. 3. 3.]
 [3. 3. 0. 2. 2. 3. 3.]
 [3. 3. 0. 1. 0. 3. 3.]
 [2. 2. 2. 1. 0. 2. 3.]
 [2. 1. 1. 1. 0. 2. 0.]]
